### PR TITLE
Initial work on replacing tween with Animated - Pass 2

### PR DESCRIPTION
**Pull request by rgoldiez**
New PR with new prop `useNativeDriver` which is defaulted to true.

Changed the offset to open the draw from left/right to translateX.

Tweaked the dx offset while panning to better track the finger.

### CODE REVIEW

**Comment by rt2zz** [comment]
Firstly awesome!

I assume this breaks some number of the existing props like tweenHandler? I will optimistically give this a test drive this weekend and we can go from there.

**Comment by rgoldiez** [comment]
I haven't cleaned up (removed) the tween props yet. So you can provide them but they are not used. 

There's a new prop useNativeDriver that is defaulted to true. Probably want this defaulted to false. I see a weird bug only initially with useNativeDriver the the drawer is opened the very first time. Note that this prop is simply passed to the Animation method. 

Keep in mind that my use is a left, static drawer. I haven't don't any testing on right side drawers and limited testing with overlay and displace types.

**Comment by ippa** [comment]
Great work rgoldiez, going to try this out soon. Question, do you have any idea how close this will be to a "100% native" feeling once this is done?

**Comment by rgoldiez** [comment]
@ippa - Hard for me to say.  This PR simply attempts to replace `tween` to move the drawer (programmatically or with a gesture) to `Animated`.  I encourage you to try it and let me know where it's breaking `Drawer` functionality and anything that doesn't feel native.

If your implementation of `Drawer` sometimes feels laggy, it could be related to the content you have in your main or drawer views.  I did some work recently to an app that uses `Drawer` and found some serious lagginess in the Drawer's responsiveness (but not my scrollview in the main content).  This isn't a deficiency of `Drawer`, per say.  It's that the JS thread is overloaded.  The same issue can/will be seen with this PR since the pan/gesture responder relies on the JS.  If this is an issue you experience, I encourage you to play around with `InteractionManger` and some of the methods it provides.  You can make a meaningful improvement to responsiveness if you have content that puts a lot of load on the JS thread.

**Comment by ippa** [comment]
@rgoldiez 

Did some testing in one of my apps with your fork of react-native-driver. I can't get the sidebar to show with it. Snippet from my code, anything wrong?
````
<Drawer
    open={sidebar.visible}
    styles={{mainOverlay: { backgroundColor: 'black', opacity: 0}}}
    onOpen={() => dispatch({type: 'SHOW_SIDEBAR'}) }
    onClose={() => dispatch({type: 'HIDE_SIDEBAR'}) }
    type="overlay"
    content={ <SidebarContent
                sidebar={sidebar}
                dispatch={dispatch}
                version={version}
                build={build}
                codePushVersion={codePushVersion}
              />
            }
    tweenHandler={ ratio => ({mainOverlay: {opacity: ratio / 2} }) }
    openDrawerOffset={100}
    closedDrawerOffset={0}
    panOpenMask={20}
    captureGestures={true}
    negotiatePan={true}
    panCloseMask={windowSize.width}
  >
    {children}
  </Drawer>;

**Comment by ippa** [comment]
@rt2zz @rgoldiez any progress on this? Would be so nice with a topnotch drawer-experience. On a fairly recent testphone (nexus 5) it kind of stutters here and there. It's not that supersmooth native-feeling that mobileusers has come to expect.

I'm up for testing new stuff.. tried testing rgoldiez fork but didn't succeed (as you can see in my last msg from dec)

**Comment by rgoldiez** [comment]
@ippa  - Sorry.... I haven't had time to get back to looking at this 🙁

**Comment by rt2zz** [comment]
There are I think two paths forward for this project:
- finish off this PR and merge
- start recommending other solutions such as react-navigation

I am all ears. I do love react-native-drawer, but it is starting to show its age and would need a significant revamp to keep this boat moving in the right direction. 

Thoughts and PR's welcome!

**Comment by kdenz** [comment]
Is there any update to implementation of Animated? @rt2zz @rgoldiez

**Comment by rt2zz** [comment]
same here, sadly I think it is time to deprecate this module! I still believe there is potential utility in the customizability of react-native-drawer, but in its current state it just does not cut it performance wise. I will update the note in the readme to be more emphatic. If anyone does want to take over this PR, I will gladly add maintainers.

**Comment by peacechen** [comment]
This simple drawer component is a good alternative to the convoluted, ever-changing react-navigation kitchen sink.  I'd like to help merge this PR to make it more performant.  Bumping the major version to 3 would prevent existing users from breakage, and allow this package to move forward with better features and performance.  If you don't mind, please add me as a collaborator on this repo and npm.  Thanks 👍

**Pull request closed without merging**
