### PR TITLE
fix drawer side "right" margin progressively increase

### PR DESCRIPTION
**Pull request by mtiziano**
also reported here https://github.com/root-two/react-native-drawer/issues/349

### CODE REVIEW

**Comment by mstf0ta-app** [comment]
thank you very much .
this solve my problem too

**Comment by ItsNoHax** [comment]
Not a good fix, still breaks on iPhone PLUS or iPhone X models.

**Comment by mtiziano** [comment]
Thanks @ItsNoHax, it was a problem handling onPanResponderMove.
Now it should be fine

**Comment by ItsNoHax** [comment]
Take into account the original maintainer no longer looks at MRs so don't expect this to be merged.

**Comment by engorila** [comment]
I don't understand your solution... and it not run on iPad.

To fix all you have to change `updatePosition` method. Add Math.round inside switch (in my case overlay):

`drawerProps[this.props.side] = Math.round(-this.getDeviceLength() + this._offsetOpen + this._length)`

**Comment by ItsNoHax** [comment]
@engorila Your fix doesn't work either, it still happens eventhough at a much smaller pace. I don't see how a Math.round can be a proper fix. I feel like you guys are programming by guessing.

**Comment by gersonmontenegro** [comment]
@engorila thanks, works fine for me, even in real devices like iPhone 5 and iPad mini, as in emulators.

**Comment by SupriyaKalghatgi** [comment]
@rt2zz When can we get this merged?

**Comment by amitmaurya0** [comment]
can any one tell me how and where to implement this updatePosition ?

**Comment by anjalsan** [comment]
@SupriyaKalghatgi When this fix reflect on nativebase?

**Comment by anjalsan** [comment]
@amitmaurya0 inside node_modules/react-native-drawer/index.js line number 210 in the latest version. you can change that line with this
`drawerProps[this.props.side] = Math.round(-this.getDeviceLength() + this._offsetOpen + this._length)`

**Comment by xralphack** [comment]
#352

**Comment by sdg9** [comment]
For what it's worth I did a git bisect between the react-native 0.54.x and 0.55.x and found that [this commit in React Native](https://github.com/facebook/react-native/commit/f91f7d91a1e937785438d568ff629d00307ca75a) is what causes the problem, at least when testing on iPhone X simulator.  I don't have a solution yet.

**Review by silkyland — APPROVED** [review]

**Comment by madyankin** [comment]
@rt2zz pleeeeease!

**Comment by roycclu** [comment]
Have tried @numez and @anjalsan . 
Works on most models. 
Doesn't work on iPhoneX. 
It reduces the problem to a much slower pace, but still there. 

Only appears on RN 0.55, so reverting back to RN.0.54. 
Can anyone confirm if this still an issue in RN 0.56?

**Comment by madyankin** [comment]
@roycclu you can try my fork https://github.com/outpunk/react-native-drawer.

**Comment by roycclu** [comment]
@outpunk sure will try.
Can you make a PR so it's obvious to see the changes you made against main repository?
Thanks.

**Comment by madyankin** [comment]
@roycclu Actually, I did ;) 
https://github.com/root-two/react-native-drawer/pulls/outpunk

**Comment by roycclu** [comment]
@outpunk 
dood, doesn't work. 
looks like the only change you made was line 30 in tweener.js
```
this._config.onFrame(Math.round(tweenVal));
```
Problem still present on iPhoneX, just to a smaller degree

**Comment by madyankin** [comment]
@roycclu Can the bug be reproduced in iOS simulator?

**Comment by nguyenvanphuc2203** [comment]
any update ?

**Comment by roycclu** [comment]
The bug can be repro in simulator. 
Currently I reverted down to RN 53. (RN54 also works.)

To repro, make a horizontal listview in the main page, and as you open and close drawer, the cells in the listview shrink. 

Currently busy with our app launch. Will try making a repro when I have time. But yea problem is fairly obvious.

**Comment by madyankin** [comment]
@roycclu It would be nice to have one. I'm a bit busy to tackle this now, but I have to support iPhone X, too. So I'll dig into this later if nobody solves the issue until then.

**Comment by uc-asa** [comment]
drawerProps[this.props.side] = Math.round(-this.getDeviceLength() + this._offsetOpen + this._length)

That's work for me.

Thanks @amitmaurya0

**Comment by jdestep93** [comment]
Works well thanks @amitmaurya0

**Comment by irqequirecoffee** [comment]
Just stopping by to say thanks to @amitmaurya0, this fix worked for me as well.

**Comment by rt2zz** [comment]
thanks @amitmaurya0 !

**Comment by predator-1** [comment]
You can make even openDrawerOffset. I had openDrawerOffset={0.33} and it has bug. But 
openDrawerOffset={0.34} all ok

**Comment by adnan1naeem** [comment]
@anjalsan solution is working fine please release new version with the prescribed solution

**Comment by chiasheang** [comment]
> @amitmaurya0 inside node_modules/react-native-drawer/index.js line number 210 in the latest version. you can change that line with this
> `drawerProps[this.props.side] = Math.round(-this.getDeviceLength() + this._offsetOpen + this._length)`

Works on most models.
Doesn't work on iPhoneX and iPhone Plus models when I set openDrawerOffset = {0.3} and open it for more than 7 times 
But working fine if I set openDrawerOffset = {0.28} 

Hope someone can figure out what are the problems.

**Pull request merged**
